---
author: Ilmars
title: habits
references:
- id: story_of_philosophy_will_durant
  author:
  - family: Durant
    given: Will
  title: "The story of philosophy: The Lives and Opinions of the World's Greatest Philosophers"
  publisher: Simon & Schuster
  type: book
  issued:
    year: 1926
output: html_document 
---
# *"We are what we repeatedly do. Excellence, then is not an act, but a habit."* [@story_of_philosophy_will_durant]

## How to break a bad habit
I want to stop doing **X**

1. Make it as hard as possible to do **X**
	* If its based on consumables (e.g. junkfood) - don't keep it at your home if possible
	* If its based on inconsumables (e.g. smartphone) - keep it as far as away as possible
2. Every time you catch yourself returning to the habit, stop yourself
3. Get busy / Distract yourself

## How to form a habit
I want to do **X** regularly

#### Simplify it / break it down
* focus on specifics
* make one change at a time

#### Make it as easy as possible to follow
* e.g. Keep fresh fruit instead of junkfood at home
* make associated items as available and visible as possible
* start very small - *"How much of **X** is stupidly easy to do?"*

#### Build habits on habits
Each of us already have some built-in habits upon which we can build.

* create morning, evening routines
* you can add small habits to:
	* every time you eat
	* every time you go to the bathroom
	* every break you take at work
	* anything you do regularly...

#### Don't
* Don't try to form multiple habits at once
* Don't attempt making large changes in a short amount of time
* Don't do so much of **X** that you start disliking it

### You should be saying:
*"It's already here... So i might as well..."*

*"That's ridiculously easy, i can surely do that!"*

### If you find yourself saying:
*"I already did **Y** amount of **X** yesterday... I'll skip today"* - you should lower the frequency/amount of **X**

## References
