---
title: Wim Hof breathing method
author: Ilmars
---

## The power breath
A power breath consists of two parts:

1. a full inhalation - lungs are fully inflated, belly moves outward, chest rises
2. the letting go of your breath - let go of the air, don't push it, not everything has to come out

## Standard method
1. 30-45 power breaths
2. exhale fully
3. hold breath until no longer able
4. take a deep breath and hold it for 10-15 seconds
5. repeat 1. - 4. for 3-4 rounds total

## Walking method
**BE WEARY: THIS IS DANGEROUS AND CAN LEAD TO PASSING OUT**
1. 40-50 power breaths
2. exhale fully
3. hold breath until very uncomfortable
4. take a deep breath
5. squeeze your body, hold breath for 10-15 steps (keep squeezing as long as you are dizzy)
6. exhale, keep walking

I haven't tried multiple rounds of the walking method as one round helps **a lot**. Doing multiple rounds seems dangerous because this method gets me quite dizzy. This method seems more powerful than the regular method as I can instantly feel a primoridal surge of energy throughout my body as if I were prepared for a battle.

